networks:
  dockernet:
    external: true
services:
  philander-weerapp:
    image: philander_weerapp:V1
    container_name: philander_weerapp:V1
    working_dir: /app
    volumes:
      - ../:/app  # Mount de projectmap in de container
    environment:
      - WEATHER_API_KEY=your_api_key  # Voeg je API-sleutel hier toe
    command: python organized_server_script_v2.6.py

