version: '3.8'

services:
  philander-weerapp:
    build:
      context: ..
    container_name: philander_weerapp
    environment:
      - WEATHER_API_KEY=your_api_key
    volumes:
      - ../:/app
    command: python organized_server_script_v2.6.py
